**Indexing and Slicing**

Indexing means accessing a single element from your data using its position.
**Syntax:**
arr = [10, 20, 30, 40]

arr[0] → 10

arr[2] → 30
Slicing means extracting a subset (a part) of your data.
Syntax:
arr[start : end : step]

Example:
arr = [10, 20, 30, 40, 50]

arr[1:4] → [20, 30, 40]

arr[:3] → [10, 20, 30]

arr[2:] → [30, 40, 50]

arr[::2] → [10, 30, 50]

In [ ]:
import numpy as np

# Sample dataset (rows = samples, columns = features + target)
data = np.array([
    [25, 50000, 1],
    [30, 60000, 0],
    [35, 65000, 1],
    [40, 70000, 0]
])

print("Dataset:\n", data)

# 🔸 Indexing (access single value)
print("\nIndexing Example:")
print("Value at row 1, column 2:", data[1][2])   # Output: 0

# 🔸 Slicing (access multiple values)
print("\nSlicing Examples:")

# All rows, first column (Age)
ages = data[:, 0]
print("Ages:", ages)

# All rows, last column (Target)
target = data[:, -1]
print("Target:", target)

# First 2 rows
first_two_rows = data[0:2, :]
print("First 2 rows:\n", first_two_rows)

# 🔸 ML-style split (features and labels)
X = data[:, :-1]   # all columns except last
y = data[:, -1]    # last column

print("\nFeatures (X):\n", X)
print("Labels (y):\n", y)

Dataset:
 [[   25 50000     1]
 [   30 60000     0]
 [   35 65000     1]
 [   40 70000     0]]

Indexing Example:
Value at row 1, column 2: 0

Slicing Examples:
Ages: [25 30 35 40]
Target: [1 0 1 0]
First 2 rows:
 [[   25 50000     1]
 [   30 60000     0]]

Features (X):
 [[   25 50000]
 [   30 60000]
 [   35 65000]
 [   40 70000]]
Labels (y):
 [1 0 1 0]


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print(arr[:3])
print(arr[2:])
print(arr[::2])
print(arr[-3:-1])
print(arr[1:4:2])
print(arr[::2])
print(arr[1:4:2])

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]
[30 40]
[20 40]
[10 30 50]
[20 40]


In [ ]:
import numpy as np

# Dataset (Age, Salary, Purchased)
data = np.array([
    [25, 50000, 1],
    [30, 60000, 0],
    [35, 65000, 1]
])

print("Dataset:\n", data)

# 🔸 Single value indexing
print("\nValue at row 0, column 1:", data[0][1])

# 🔸 Alternative way
print("Value at row 2, column 0:", data[2, 0])

# 🔸 Negative indexing
print("Last row:", data[-1])
print("Last value:", data[-1, -1])

Dataset:
 [[   25 50000     1]
 [   30 60000     0]
 [   35 65000     1]]

Value at row 0, column 1: 50000
Value at row 2, column 0: 35
Last row: [   35 65000     1]
Last value: 1


In [ ]:
X = data[:, :-1]   # features
y = data[:, -1]    # target

print("First sample features:", X[0])
print("First sample label:", y[0])

First sample features: [   25 50000]
First sample label: 1
